// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EnqueueJobs(arg1:number,arg2:Array<main.Instance>):Promise<string>;

export function GetSavedDirectory():Promise<string>;

export function PreprocessLog(arg1:string,arg2:string):Promise<main.PreprocessResponse>;

export function SelectDirectory():Promise<string>;

export function StartMonitoringJob(arg1:number):Promise<void>;
