// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EnqueueJobs(arg1:number,arg2:Array<main.Instance>):Promise<string>;

export function GetPremiumConfig():Promise<Record<string, string>>;

export function GetSavedDirectory():Promise<string>;

export function GetTheme():Promise<string>;

export function GetUploaderServers():Promise<Array<main.UploaderServer>>;

export function GetWowDirectory():Promise<string>;

export function OpenAllLogsPage():Promise<void>;

export function OpenLogPage(arg1:number):Promise<void>;

export function PreprocessLog(arg1:string,arg2:string):Promise<main.PreprocessResponse>;

export function SavePremiumConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectWowDirectory():Promise<string>;

export function SetTheme(arg1:string):Promise<void>;

export function StartMonitoringJob(arg1:number):Promise<void>;

export function UpdateAddonRankings(arg1:string,arg2:number):Promise<string>;
