// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnqueueJobs(arg1, arg2) {
  return window['go']['main']['App']['EnqueueJobs'](arg1, arg2);
}

export function GetSavedDirectory() {
  return window['go']['main']['App']['GetSavedDirectory']();
}

export function PreprocessLog(arg1, arg2) {
  return window['go']['main']['App']['PreprocessLog'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartMonitoringJob(arg1) {
  return window['go']['main']['App']['StartMonitoringJob'](arg1);
}
