// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AbandonAutoUploadInstanceSelection():Promise<void>;

export function BrowseAddonRankingsJSON(arg1:string,arg2:number,arg3:string):Promise<string>;

export function CancelAutoUploadServerDrift():Promise<void>;

export function CheckAutoUploadPremiumNow():Promise<boolean|string>;

export function CommitAddonRankingsJSON(arg1:string):Promise<string>;

export function CommitGuildRankingsJSON(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CommitRaidPartyRankingsJSON(arg1:string,arg2:string):Promise<string>;

export function DisableAutoUpload():Promise<void>;

export function EnqueueAutoUploadJobs(arg1:number,arg2:Array<main.Instance>,arg3:string,arg4:string):Promise<string>;

export function EnqueueJobs(arg1:number,arg2:Array<main.Instance>):Promise<string>;

export function EstablishAutoUploadBaseline(arg1:string):Promise<main.BaselinePreview>;

export function FetchGuildCharacterRankingsJSON(arg1:number,arg2:string):Promise<string>;

export function FetchGuildInfoJSON(arg1:number):Promise<string>;

export function FetchLeaderboardFilterBossesJSON(arg1:number,arg2:number,arg3:string,arg4:number):Promise<string>;

export function FetchLeaderboardFilterDifficultiesJSON(arg1:number,arg2:number,arg3:number):Promise<string>;

export function FetchLeaderboardFilterRaidsJSON(arg1:number,arg2:number):Promise<string>;

export function FetchLeaderboardSeasonsConfigJSON():Promise<string>;

export function FetchRosterCharacterRankingsJSON(arg1:string,arg2:string):Promise<string>;

export function GetApiBaseURL():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetAutoUploadSettings():Promise<main.AutoUploadSettingsResponse>;

export function GetAutoUploadWatcherStatus():Promise<main.AutoUploadWatcherStatus>;

export function GetMinimizeToTray():Promise<boolean>;

export function GetPremiumConfig():Promise<Record<string, string>>;

export function GetSavedDirectory():Promise<string>;

export function GetTheme():Promise<string>;

export function GetUploaderServers():Promise<Array<main.UploaderServer>>;

export function GetWowDirectory():Promise<string>;

export function IsServerAllowedForAutoUpload(arg1:string):Promise<boolean>;

export function OpenAllLogsPage():Promise<void>;

export function OpenLogPage(arg1:number):Promise<void>;

export function PrepareAutoUploadStagingNow():Promise<main.AutoUploadWatcherStatus>;

export function PreprocessLog(arg1:string,arg2:string):Promise<main.PreprocessResponse>;

export function ResolveAutoUploadServerDrift(arg1:string):Promise<void>;

export function ResumeAutoUpload():Promise<void>;

export function SaveDefaultServer(arg1:string):Promise<void>;

export function SavePremiumConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectWowDirectory():Promise<string>;

export function SetMinimizeToTray(arg1:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartMonitoringJob(arg1:number):Promise<void>;

export function StartMonitoringJobWithTailRefresh(arg1:number,arg2:string):Promise<void>;

export function UpdateAddonRankings(arg1:string,arg2:number):Promise<string>;
