// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EnqueueJobs(arg1, arg2) {
  return window['go']['main']['App']['EnqueueJobs'](arg1, arg2);
}

export function GetAddonSavedVariablesPath() {
  return window['go']['main']['App']['GetAddonSavedVariablesPath']();
}

export function GetPremiumConfig() {
  return window['go']['main']['App']['GetPremiumConfig']();
}

export function GetSavedDirectory() {
  return window['go']['main']['App']['GetSavedDirectory']();
}

export function GetUploaderServers() {
  return window['go']['main']['App']['GetUploaderServers']();
}

export function OpenAllLogsPage() {
  return window['go']['main']['App']['OpenAllLogsPage']();
}

export function OpenLogPage(arg1) {
  return window['go']['main']['App']['OpenLogPage'](arg1);
}

export function PreprocessLog(arg1, arg2) {
  return window['go']['main']['App']['PreprocessLog'](arg1, arg2);
}

export function SavePremiumConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePremiumConfig'](arg1, arg2, arg3);
}

export function SelectAddonSavedVariablesFile() {
  return window['go']['main']['App']['SelectAddonSavedVariablesFile']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartMonitoringJob(arg1) {
  return window['go']['main']['App']['StartMonitoringJob'](arg1);
}

export function UpdateAddonRankings(arg1, arg2) {
  return window['go']['main']['App']['UpdateAddonRankings'](arg1, arg2);
}
